apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-switch
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/aquelepaulo/oci-resource-manager-argocd-test-switch.git
    targetRevision: main
    path: kubernetes/app
  destination:
    server: https://kubernetes.default.svc
    namespace: gitops-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
